### ISSUE TITLE
Traceback involving rev b36afb8

### ISSUE THREAD

**Issue by nth10sd** [Pernosco/pernosco-submit#6]
I get a pernosco traceback that goes away by checking out the parent of this rev b36afb8:

```
Traceback (most recent call last):
  File "./pernosco-submit", line 701, in <module>
    repo_paths = package_source_files()
  File "./pernosco-submit", line 549, in package_source_files
    (repo_mount, modified_files) = analyze_repo(repo_path, files)
  File "./pernosco-submit", line 489, in analyze_repo
    return analyze_hg_repo(repo_path, files)
  File "./pernosco-submit", line 463, in analyze_hg_repo
    remotes = hg_remotes(repo_path)
  File "./pernosco-submit", line 426, in hg_remotes
    url_generator = hg_remote_url_to_source_url_generator(url)
  File "./pernosco-submit", line 293, in hg_remote_url_to_source_url_generator
    if m.group(2) == 'try':
IndexError: no such group
```

My `.hg/hgrc` looked like:

```
[paths]

default = https://hg.mozilla.org/mozilla-central
```

pernosco-submit's git config looks like:

```
$ cat .git/config 
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[remote "origin"]
        url = https://github.com/Pernosco/pernosco-submit
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
        remote = origin
        merge = refs/heads/master
```

@rocallahan do you have an idea why?

**Comment by khuey** [comment]
The last two csets I just pushed should fix this, please reopen if it doesn't work.

Thanks for reporting.
